### ISSUE TITLE
希望右侧可以增加大纲栏

### ISSUE THREAD

**Issue by ReiseReise** [sylviaxgj/typora-forest-theme#10]
每次都要切换，希望在预览页面可以在右侧增加上文章大纲栏

**Comment by sylviaxgj** [comment]
这个可以去Typora官方反馈看看，目前Mac OS上已经支持的， Windows暂时没有。
以下为Mac OS上界面：
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/22345930/235917985-8b7f7bd9-2f8b-4edc-816a-474ed3ef5d77.png">
