### ISSUE TITLE
在搜索查找关键词时，字体颜色不突出【图片】

### ISSUE THREAD

**Issue by GWNLP** [sylviaxgj/typora-forest-theme#12]
![image](https://user-images.githubusercontent.com/118590347/216827137-b37088b8-3f3c-4a54-9475-61652a0cefd3.png)
<img width="425" alt="20230205_230201_326_copy" src="https://user-images.githubusercontent.com/118590347/216827157-753a2caa-8b1b-406b-a13c-af6ee2608929.png">

**Comment by GWNLP** [comment]
忘记感谢作者发布的这款主题了 感谢

**Comment by ocean-99** [comment]
forest.css 640行, var()改为想要的颜色即可，我改成了var(--theme-primary-color). 来自版本v0.1.6

**Comment by sylviaxgj** [comment]
已修复，感谢反馈！这个是windows系统下的bug，之前主要基于Mac测试的。[v0.1.7](https://github.com/sylviaxgj/typora-forest-theme/releases/tag/v0.1.7)

**Comment by GWNLP** [comment]
很感谢主题作者的持续贡献

**Comment by GWNLP** [comment]
> forest.css 640行， var（）改为想要的颜色即可，我改成了var（--theme-primary-color）.来自版本v0.1.6

感谢 已解决
