### ISSUE TITLE
改变代码块选中时的颜色

### ISSUE THREAD

**Issue by xiaoyaobishizhe** [sylviaxgj/typora-forest-theme#15]
当选中代码块中的代码时，被选中的内容是白色的，字体也是白色的，看不清选择的内容，希望可以调整一下颜色，以便可以看清所选中的内容。

**Comment by sylviaxgj** [comment]
感谢支持，问题已经fixed，[v0.1.8](https://github.com/sylviaxgj/typora-forest-theme/releases/tag/v0.1.8)
