### ISSUE TITLE
请问可不可以让引用的宽度和正文的显示宽度一致

### ISSUE THREAD

**Issue by FrankirJ** [sylviaxgj/typora-forest-theme#18]
很喜欢您的作品，只是在使用过程中还是觉得引用的宽度和正文的宽度不一致稍有不适，希望可以告诉在哪里设置，或者其他建议。

**Comment by 1216892614** [comment]
草, 这个作者做完就没消息了好像. 去年五月的 PR 都还没消息, 快捷打开的菜单文件名到现在都还基本看不见...

**Comment by sylviaxgj** [comment]
感谢支持，问题已经fixed，[v0.1.8](https://github.com/sylviaxgj/typora-forest-theme/releases/tag/v0.1.8)

**Comment by FrankirJ** [comment]
Thank you
