### ISSUE TITLE
这个作者好像没消息了, 确实是很棒的主题, 想开个 Fork 先维护, 要是他回来了再合并回去.

### ISSUE THREAD

**Issue by 1216892614** [sylviaxgj/typora-forest-theme#19]
草, 这个作者做完就没消息了好像. 去年五月的 PR 都还没消息, 快捷打开的菜单文件名到现在都还基本看不见...
我想开个 Fork 先维护, 后面再合并不知道各位意见如何?

**Comment by sylviaxgj** [comment]
抱歉😂，因为工作比较忙，一直没有时间验证和修复问题，并且个人使用的是Mac OS，验证Windows的相关问题会稍微麻烦一些。最近会找时间集中进行一波优化，感谢大家的支持和喜爱~

**Comment by FrankirJ** [comment]
没关系，支持~
