### ISSUE TITLE
INI文件段标题颜色能不能优化下

### ISSUE THREAD

**Issue by maobole** [sylviaxgj/typora-forest-theme#2]
这个主题太漂亮了，必须点赞！

有一个小建议，Code块下如果为INI格式，[main]这种颜色会是一个蓝，在深色背景下不清楚，能不能优化下？

多谢！

**Comment by sylviaxgj** [comment]
>已修复，感谢反馈！

https://github.com/sylviaxgj/typora-forest-theme/releases/tag/v0.1.5
