### ISSUE TITLE
希望可以完善侧边栏的滚动条效果

### ISSUE THREAD

**Issue by leon-zym** [sylviaxgj/typora-forest-theme#3]
在侧边栏的文件数量较多，出现滚动条的时候，显示效果不是很好。希望可以将滚动条的背景颜色改成和侧边栏主题色相同。

<img width="352" alt="Xnip2022-06-05_10-29-46" src="https://user-images.githubusercontent.com/17230055/172032507-10e59789-227b-4062-8410-c03773775762.png">

**Comment by sylviaxgj** [comment]
我这边没有复现出来，可以提供一下使用平台和软件版本号吗？
<img width="264" alt="image" src="https://user-images.githubusercontent.com/22345930/235921400-bcc08531-ea37-4f01-9642-fe3fc4c4aff6.png">

**Comment by leon-zym** [comment]
可能是当时的 Typora 的问题，现在新版本的已经不会复现了
