### ISSUE TITLE
搜索栏看不见字

### ISSUE THREAD

**Issue by WalkerGloom** [sylviaxgj/typora-forest-theme#4]
<img width="173" alt="看不见4" src="https://user-images.githubusercontent.com/50197664/173289302-f0c05ac0-b575-465e-804c-7839497b8284.png">
<img width="218" alt="看不见1" src="https://user-images.githubusercontent.com/50197664/173289309-828799c2-0267-4add-8a85-2cdcdab3c254.png">
<img width="219" alt="看不见2" src="https://user-images.githubusercontent.com/50197664/173289321-fe84fd9a-c2d2-4035-9d01-08e7152e40f7.png">
<img width="218" alt="看不见3" src="https://user-images.githubusercontent.com/50197664/173289330-6cd93331-09fa-4b1d-bc0d-5602c4a8c42f.png">

希望可以修复，感谢作者大大的付出！！

**Comment by AlinuxNooB** [comment]
我也发现了这个问题，不知是否为系统问题(win10)，作者是macos。另外这个主题真的太棒了。

**Comment by zenghongji** [comment]
> 我也发现了这个问题，不知是否为系统问题(win10)，作者是macos。另外这个主题真的太棒了。

同样感谢作者的主题，非常清爽好看。我在Windows11也遇到这样的问题。我通过注释forest.css文件中的 sidebar search的样式来解决的，如下：
```
/* sidebar search*/
.sidebar-menu .ty-sidebar-search-panel #file-library-search-input {
  /* color: var(--white-color); */
}
```

**Comment by sylviaxgj** [comment]
已修复 #12
