### ISSUE TITLE
[`title`](url) 链接样式不明显，需要鼠标 hover 之后才能发现这是个链接。

### ISSUE THREAD

**Issue by GreatAuk** [sylviaxgj/typora-forest-theme#7]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/20253809/180965526-87a671a1-4ccc-4a84-bda8-47cd5b7b9e96.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/20253809/180965629-803538f4-11b5-4aa1-b6f0-ae3161e791e3.png">

**Comment by sylviaxgj** [comment]
感谢支持，问题已经fixed，[v0.1.8](https://github.com/sylviaxgj/typora-forest-theme/releases/tag/v0.1.8)
