### ISSUE TITLE
希望书写的字体能再大一点 .

### ISSUE THREAD

**Issue by YanHuiLi** [sylviaxgj/typora-forest-theme#8]
书写的字体有点小，希望能够再大一点。

**Comment by sylviaxgj** [comment]
字体大小可以在【偏好设置】-【外观】-【字体大小】中进行自定义的。
<img width="678" alt="image" src="https://user-images.githubusercontent.com/22345930/235920074-a95e7dc8-0307-4e0f-8fe5-4bfde878ae6b.png">
